[2020-07-30 10:52:42] Rest Api task 1
vishakraman/d8project pull request #8
Opened 2020-07-30 05:23 UTC by vishakraman

2020-07-30 16:46 UTC, girish06 requested changes

2020-07-30 16:46 UTC, girish06 commented on web/modules/custom/form/src/Plugin/rest/resource/ExampleGetRestResource.php
> +      dsm($node);
remove dsm

2020-07-30 16:46 UTC, girish06 commented on web/modules/custom/form/config/install/rest.resource.demo_resource.yml
> +id: example_get_rest_resource
can you please explain why this yml is required

2020-07-30 16:53 UTC, girish06 requested changes

2020-07-30 16:53 UTC, girish06 commented on web/modules/custom/form/src/Plugin/rest/resource/ExampleGetRestResource.php
> +          'image'=>$node->field_image_api->entity->getFileUri(),
do validate

2020-07-30 16:53 UTC, girish06 commented on web/modules/custom/form/src/Plugin/rest/resource/ExampleGetRestResource.php
> +    $nids = \Drupal::entityQuery('node')->condition('type','api')->execute();
only published content

2020-08-03 05:56 UTC, vishakraman commented
Fixed and pushed

2020-08-05 16:52 UTC, girish06 approved these changes

2020-08-05 16:52 UTC, merged